config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  Spree::Core::Engine.add_routes do
    namespace :admin, path: Spree.admin_path do
      resources :orders do
        member do
          post :resend_shipped
        end
      end
    end
  end
end

app/models/spree/order_decorator.rb
module Spree
  module OrderDecorator
    def payment_state_readable
      return 'refunded' if self.refunds.any?
      payment_state
    end

    def can_approve?
      completed? && !approved?
    end
  end
end

Spree::Order.prepend Spree::OrderDecorator

app/models/spree/shipment_decorator.rb
module Spree
  module ShipmentDecorator
    def tracking_link
      if self.carrier.blank? or self.tracking.blank?
        return self.tracking_url
      end
      SpreeAdminOnepageOrder::Carriers.find(self.carrier).tracking_link(self.tracking) rescue self.tracking_url
    end
  end
end

Spree::Shipment.prepend Spree::ShipmentDecorator

app/controllers/spree/admin/orders_controller_decorator.rb
module Spree
  module Admin
    module OrdersControllerDecorator
      def self.prepended(base)
        base.helper Spree::CarrierHelper
      end

      def show
        load_order
        @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_BACK_END) unless @order.completed?
      end

      def resend
        OrderMailer.confirm_email(@order.id, true).deliver_later
        flash[:success] = Spree.t(:order_email_resent)

        redirect_back fallback_location: spree.admin_order_url(@order)
      end

      def resend_shipped
        load_order
        @order.shipments.each do |shipment|
          ShipmentMailer.shipped_email(shipment.id).deliver_later
        end

        flash[:success] = Spree.t(:order_shipment_email_resent)
        redirect_back fallback_location: spree.admin_order_url(@order)
      end
    end
  end
end


Spree::Admin::OrdersController.prepend Spree::Admin::OrdersControllerDecorator

app/controllers/spree/admin/payments_controller_decorator.rb
module Spree::Admin::PaymentsControllerDecorator

  def index
    redirect_to admin_order_url(@order)
  end
end

Spree::Admin::PaymentsController.prepend Spree::Admin::PaymentsControllerDecorator

app/controllers/spree/api/v1/shipments_controller_decorator.rb
module Spree
  module Api
    module V1
      module ShipmentsControllerDecorator
        def update
          @shipment = ::Spree::Shipment.accessible_by(current_ability, :update).readonly(false).find_by!(number: params[:id])

          @shipment.update_attributes_and_order(shipment_params)

          respond_with(@shipment.reload, default_template: :show)
        end

      end
    end
  end
end

Spree::Api::V1::ShipmentsController.prepend Spree::Api::V1::ShipmentsControllerDecorator

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelperDecorator
    def link_to_carrier_tracking(shipment, options = {})
      return unless shipment.tracking && shipment.shipping_method

      options[:target] ||= :blank

      tracking_text = if shipment.carrier.blank?
                        shipment.tracking
                      else
                        shipment.carrier + " " + shipment.tracking
                      end
      if shipment.tracking_url
        link_to(tracking_text, shipment.tracking_link, options)
      else
        content_tag(:span, tracking_text)
      end
    end
  end
end

Spree::BaseHelper.prepend Spree::BaseHelperDecorator

app/helpers/spree/carrier_helper.rb
module Spree
  module CarrierHelper
    def link_to_carrier_tracking(shipment, options = {})
      return unless shipment.tracking && shipment.shipping_method

      options[:target] ||= :blank

      tracking_text = if shipment.carrier.blank?
                        shipment.tracking
                      else
                        shipment.carrier + " " + shipment.tracking
                      end
      if shipment.tracking_url
        link_to(tracking_text, shipment.tracking_link, options)
      else
        content_tag(:span, tracking_text)
      end
    end
  end
end

app/views/spree/admin/orders/_adjustments_manifest.html.erb
<% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
  <tr class="total">
    <td>
      <strong><%= label %>:</strong>
    </td>
    <td class="total">
                <span>
                  <%= Spree::Money.new(
                          adjustments.sum(&:amount),
                          currency: adjustments.first.order.try(:currency)
                      ) %>
                </span>
    </td>
  </tr>
<% end %>

app/views/spree/admin/orders/_form.html.erb
<div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render 'spree/admin/shared/error_messages', target: @line_item %>
  <% end %>

  <% if Spree::Order.checkout_step_names.include?(:delivery) and @order.shipments.any? %>
    <%= render partial: "spree/admin/orders/shipment", collection: @order.shipments.order(:created_at), locals: {order: order} %>
  <% else %>
    <%= render "spree/admin/orders/line_items", order: order %>
  <% end %>

  <%= javascript_tag do %>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
      shipments.push(
      <%== shipment.as_json(
               root: false,
               only: [
                   :id, :tracking, :number, :state, :stock_location_id
               ], include: [
               :inventory_units, :stock_location
           ]).to_json
      %>
      );
    <% end %>

    <%= render partial: 'spree/admin/shared/update_order_state', formats: [:js], handlers: [:erb] %>
  <% end %>
</div>

app/views/spree/admin/orders/_order_actions.html.erb
<% content_for :page_actions do %>
  <% if can?(:fire, order) %>
    <%= event_links(order, events) %>
  <% end %>

  <% if can?(:resend, order) and order.completed? %>
    <%= button_link_to Spree.t(:resend, scope: 'admin.order.events', default: Spree.t(:resend)),
                       resend_admin_order_url(order),
                       method: :post,
                       icon: 'envelope.svg'
    %>
  <% end %>
  <% if can?(:resend, order) and order.completed? and order.shipments.any? and order.shipments.first.shipped?%>
    <%= button_link_to Spree.t(:resend_shipment, scope: 'admin.order.events', default: Spree.t(:resend_shipment)),
                       resend_shipped_admin_order_url(order),
                       method: :post,
                       icon: 'envelope.svg'
    %>
  <% end %>
<% end %>

app/views/spree/admin/orders/_order_sidebar.html.erb
<% content_for :page_title do %>
  Order #<%= @order.number %>
<% end %>

<% content_for :sidebar do %>
  <% guest = @order.user.nil? %>
  <div class="card mb-3">
    <div class="card-header">
      <h3 class="card-title mb-0 h5"><%= Spree.t(:customer) %>
      </h3>
    </div>
    <div class="card-body">
      <% unless @order.bill_address.nil? %>
        <p class="card-text"><%= @order.bill_address.firstname %> <%= @order.bill_address.lastname %>
          <% if guest %>
            <span class="badge badge-secondary"><%= Spree.t(:guest) %></span>
          <% end %>
      <% else %>
        <%= Spree.t(:no_customer_info_yet) %>
      <% end %>
      <br>
      <a href="mailto:<%= @order.user.try(:email) || @order.email %>" target="_blank"><%= @order.user.try(:email) || @order.email %></a>
      </p>
    </div>
  </div>
  <% unless @order.shipping_address.nil? %>
    <div class="card mb-3">
      <div class="card-header">
        <h3 class="card-title mb-0 h5"> <%= Spree.t(:shipping_address) %></h3>
      </div>
      <div class="card-body">

        <%= render 'spree/admin/shared/address', address: @order.shipping_address %>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title mb-0 h5"><%= Spree.t(:billing_address) %></h3>
      </div>
      <div class="card-body">
        <%= render 'spree/admin/shared/address', address: @order.billing_address %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/spree/admin/orders/_payment_summary.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h3 class="card-title mb-0 h5"><%= Spree.t(:summary) %></h3>
  </div>
  <div class="table-responsive">
    <table class="table table-condensed table-bordered" id="order_tab_summary" data-hook>
      <tbody class="additional-info">
      <tr>
        <td id="order_status" width="35%" data-hook>
          <strong><%= Spree.t(:status) %>:</strong>
        </td>
        <td>
          <% if @order.payment_state_readable.present? && @order.payment_state_readable == 'refunded' %>
            <span class="state badge badge-<%= @order.payment_state_readable %> text-uppercase">
              <%= Spree.t(@order.payment_state_readable, scope: :payment_states, default: [:missing, "none"]) %>
            </span>
          <% else %>
          <span class="state badge badge-<%= @order.state %> text-uppercase">
            <%= Spree.t(@order.state, scope: :order_state) %>
          </span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td data-hook='admin_order_tab_subtotal_title'>
          <strong><%= Spree.t(:subtotal) %>:</strong>
        </td>
        <td id='item_total'>
          <%= @order.display_item_total.to_html %>
        </td>
      </tr>

      <% if @order.checkout_steps.include?("delivery") && @order.ship_total > 0 %>
        <tr>
          <td data-hook='admin_order_tab_ship_total_title'>
            <strong><%= Spree.t(:ship_total) %>:</strong>
          </td>
          <td id='ship_total'>
            <%= @order.display_ship_total.to_html %>
          </td>
        </tr>
      <% end %>

      <% if @order.included_tax_total != 0 %>
        <tr>
          <td data-hook='admin_order_tab_included_tax_title'>
            <strong><%= Spree.t(:tax_included) %>:</strong>
          </td>
          <td id='included_tax_total'>
            <%= @order.display_included_tax_total.to_html %>
          </td>
        </tr>
      <% end %>

      <%# if @order.additional_tax_total != 0 %>
<!--        <tr>-->
<!--          <td data-hook='admin_order_tab_additional_tax_title'>-->
<!--            <strong><%#= Spree.t(:tax) %>:</strong>-->
<!--          </td>-->
<!--          <td id='additional_tax_total'>-->
            <%#= @order.display_additional_tax_total.to_html %>
<!--          </td>-->
<!--        </tr>-->
      <%# end %>

      <%= render "spree/admin/orders/adjustments_manifest",
                 adjustments: @order.line_item_adjustments,
                 title: Spree.t(:line_item_adjustments)
      %>
      <%= render "spree/admin/orders/adjustments_manifest",
                 adjustments: @order.shipment_adjustments,
                 title: Spree.t(:shipment_adjustments)
      %>
      <%= render "spree/admin/orders/adjustments_manifest",
                 adjustments: @order.adjustments,
                 title: Spree.t(:order_adjustments)
      %>

      <tr>
        <td data-hook='admin_order_tab_total_title'>
          <strong><%= Spree.t(:total) %>:</strong>
        </td>
        <td id='order_total'><%= @order.display_total.to_html %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/spree/admin/orders/_payments.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h3 class="card-title mb-0 h5"><%= Spree.t(:payments) %></h3>
  </div>
  <div class="table-responsive">
    <% if @order.outstanding_balance? %>
      <div class="alert alert-info outstanding-balance">
        <%= @order.outstanding_balance < 0 ? Spree.t(:credit_owed) : Spree.t(:balance_due) %>:
        <strong><%= @order.display_outstanding_balance %></strong>
      </div>
    <% end %>

    <% if payments.any? %>
      <div data-hook="payment_list" class="mb-3 table-responsive">
        <%= render partial: 'spree/admin/payments/list', locals: {payments: payments} %>
      </div>

      <% if refunds.any? %>
        <fieldset data-hook="payment_list" class="no-border-bottom">
          <legend><%= Spree.t(:refunds) %></legend>
          <%= render partial: 'spree/admin/shared/refunds', locals: {refunds: refunds, show_actions: true} %>
        </fieldset>
      <% end %>

    <% else %>
      <div class="alert alert-info no-objects-found"><%= Spree.t(:order_has_no_payments) %></div>
    <% end %>
  </div>
</div>

app/views/spree/admin/orders/_shipment.html.erb
<div id="<%= "shipment_#{shipment.id}" %>" data-hook="admin_shipment_form" class="card mb-3">

  <%= render partial: "spree/admin/variants/split", formats: :js %>

  <div class="card-header stock-location no-borderb" data-hook="stock-location">
    <h1 class="flex-wrap align-items-center card-title mb-0 h5">
      <span class="shipment-state"><%= Spree.t("shipment_states_new.#{shipment.state}") %></span>
    </h1>
  </div>

  <div class="table-responsive">
    <table class="table table-bordered stock-contents" data-hook="stock-contents">
      <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
      <%= render 'spree/admin/orders/shipment_manifest', shipment: shipment %>

      <% unless shipment.shipped? %>
        <tr class="edit-method is-hidden total">
          <td colspan="5">
            <div class="field alpha five columns">
              <%= label_tag 'selected_shipping_rate_id', Spree.t(:shipping_method) %>
              <%= select_tag :selected_shipping_rate_id,
                             options_for_select(shipment.shipping_rates.map { |sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
                             {class: 'select2', data: {'shipment-number' => shipment.number}} %>
            </div>
          </td>
          <td class="actions text-center">
            <% if can? :update, shipment %>
              <%= link_to_with_icon 'cancel.svg', Spree.t('actions.cancel'), "#", class: 'cancel-method btn btn-outline-secondary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
              <%= link_to_with_icon 'save.svg', Spree.t('actions.save'), "#", class: 'save-method btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr class="show-method total">
        <% if rate = shipment.selected_shipping_rate %>
          <td colspan="4">
            <strong><%= rate.name %></strong>
          </td>
          <td class="total text-center">
            <%= shipment.display_cost %>
          </td>
        <% else %>
          <td colspan='5'><%= Spree.t(:no_shipping_method_selected) %></td>
        <% end %>

        <td class="actions text-center">
          <% if ((can? :update, shipment) and !shipment.shipped?) %>
            <%= link_to_with_icon 'edit.svg', Spree.t('edit'), "javascript:;", class: 'edit-method with-tip btn btn-sm btn-outline-secondary', data: {action: 'edit'}, no_text: true %>
          <% end %>
        </td>
      </tr>


      <tr class="edit-tracking is-hidden total">
        <td colspan="5">
          <table class="table table-bordered">
            <tr>
              <td><label><%= Spree.t(:tracking_number) %>:</label>
                <br>
                <%= text_field_tag :tracking, shipment.tracking, class: "form-control" %>
              </td>
              <td>
                <label><%= Spree.t(:shipping_carrier) %>:</label>
                <%= select_tag("carrier", options_from_collection_for_select(SpreeAdminOnepageOrder::Carriers.all, "code", "code", shipment.carrier), include_blank: true, class: 'select2 w-100') %>
              </td>
            </tr>
          </table>

        </td>
        <td class="actions text-center">
          <% if can? :update, shipment %>
            <%= link_to_with_icon 'cancel.svg', Spree.t('actions.cancel'), "#", class: 'cancel-tracking btn btn-outline-secondary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
            <%= link_to_with_icon 'save.svg', Spree.t('actions.save'), "#", class: 'save-tracking-carrier btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
          <% end %>
        </td>
      </tr>

      <% if order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= Spree.t(:special_instructions) %>:&nbsp;</strong><%= order.special_instructions %>
          </td>
        </tr>
      <% end %>

      <tr class="show-tracking total">
        <td colspan="5" class="tracking-value">
          <% if shipment.tracking.present? %>
            <strong><%= Spree.t(:tracking) %>:</strong> <%= link_to_carrier_tracking(shipment, target: '_blank') %>
          <% else %>
            <%= Spree.t(:no_tracking_present) %>
          <% end %>
        </td>
        <td class="actions text-center">
          <% if can? :update, shipment %>
            <%= link_to_with_icon 'edit.svg', Spree.t('edit'), "#", class: 'edit-tracking btn btn-outline-secondary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
          <% end %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_order),
                     new_admin_order_url,
                     class: "btn-success",
                     icon: 'add.svg',
                     id: 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">

        <div class="date-range-filter col-12 col-lg-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="row pb-0">
              <div class="col-12 col-md-6 mb-3 mb-md-0">
                <div class="input-group datePickerFrom"
                     data-wrap="true"
                     data-max-date="<%= params[:q][:created_at_lt] %>">
                  <%= f.text_field :created_at_gt,
                                   class: 'form-control js-filterable shadow-none',
                                   value: params[:q][:created_at_gt],
                                   placeholder: Spree.t(:starting_from),
                                   'data-input':'' %>

                  <%= render partial: 'spree/admin/shared/cal_close' %>
                </div>
              </div>
              <div class="col-12 col-md-6 mt-3 mt-md-0">
                <div class="input-group datePickerTo"
                     data-wrap="true"
                     data-min-date="<%= params[:q][:created_at_gt] %>">

                  <%= f.text_field :created_at_lt,
                                   class: 'form-control js-filterable shadow-none',
                                   value: params[:q][:created_at_lt],
                                   placeholder: Spree.t(:ending_at),
                                   'data-input':'' %>

                  <%= render partial: 'spree/admin/shared/cal_close' %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_state_eq, Spree.t(:status) %>
            <%= f.select :state_eq,
                         Spree::Order.state_machines[:state].states.map {|s| [Spree.t("order_state.#{s.name}"), s.value]},
                         { include_blank: true },
                         class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, Spree.t(:payment_state) %>
            <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map {|s| [Spree.t("payment_states.#{s}"), s]}, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_shipment_state_eq, Spree.t(:shipment_state) %>
            <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map {|s| [Spree.t("shipment_states.#{s}"), s]}, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
            <%= f.text_field :line_items_variant_sku_eq, class: 'form-control js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_store_id_in, Spree.t(:store) %>
            <%= f.select :store_id_in, Spree::Store.order(:name).pluck(:name, :id), { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">
          <div class="form-group">
            <%= label_tag :q_channel_eq, Spree.t(:channel) %>
            <%= f.select :channel_eq, Spree::Order.distinct.pluck(:channel), { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-12 col-lg-4">

          <div class="form-group">

            <div class="checkbox mt-2">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
                <%= Spree.t(:show_only_complete_orders) %>
              <% end %>
            </div>

            <div class="checkbox mt-2">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {checked: (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div>

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search.svg' %>
      </div>

    <% end %>

  </div>

<% end %>

<% if @orders.any? %>
  <div class="table-responsive">
    <table class="table" id="listing_orders" data-hook>
      <thead>
      <tr data-hook="admin_orders_index_headers">
        <th><%= sort_link @search, :number,           I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></th>
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at,   I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,     I18n.t(:created_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :state,            I18n.t(:state, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :payment_state,    I18n.t(:payment_state, scope: 'activerecord.attributes.spree/order') %></th>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, scope: 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :email,            I18n.t(:email, scope: 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :total,            I18n.t(:total, scope: 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
          <td><%= link_to order.number, admin_order_path(order) %></td>
          <td>
            <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
          </td>
          <td>
          <span class="badge badge-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
            <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
          </span>
          </td>
          <td class="no-wrap">
            <span class="badge badge-<%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span>
            <span class="filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>">
            <%= svg_icon name: "filter.svg", width: '14', height: '14' %>
          </span>
          </td>
          <td class="no-wrap">
            <% if order.payment_state %>

              <%= link_to Spree.t("payment_states.#{order.payment_state}"),
                          admin_order_payments_path(order),
                          class: "badge badge-#{order.payment_state}" %>

              <span class="filterable js-add-filter"
                    data-ransack-field="q_payment_state_eq"
                    data-ransack-value="<%= order.payment_state %>">
              <%= svg_icon name: "filter.svg", width: '14', height: '14' %>
            </span>
            <% end %>
          </td>
          <% if Spree::Order.checkout_step_names.include?(:delivery) %>
            <td class="no-wrap">
              <% if order.shipment_state %>
                <span class="badge badge-<%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></span>
                <span class="filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>">
                <%= svg_icon name: "filter.svg", width: '14', height: '14' %>
              </span>
              <% end %>
            </td>
          <% end %>
          <td class="no-wrap">
            <% if order.user %>
              <%= link_to order.email, edit_admin_user_path(order.user) %>
            <% else %>
              <%= mail_to order.email %>
            <% end %>
            <% if order.user || order.email %>
            <span class="filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>">
              <%= svg_icon name: "filter.svg", width: '14', height: '14' %>
            </span>
            <% end %>
          </td>
          <td><%= order.display_total.to_html %></td>
          <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
            <%= link_to_edit_url admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true if can?(:edit, order) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>